const express = require('express')
const router = express.Router()
const home = require('./modules/home')
const cameras = require('./modules/cameras')
const users = require('./modules/users')
const { authenticator } = require('../middleware/auth')  
router.use('/cameras', authenticator, cameras) 
router.use('/users', users)
router.use('/', authenticator, home) 
module.exports = router