const express = require('express')
const router = express.Router()
const passport = require('../config/passport')
const admin = require('./modules/admin')
const equipments = require('./modules/equipments')
const userController = require('../controllers/user-controller')
const { authenticator } = require('../middleware/auth')
const { generalErrorHandler } = require('../middleware/error-handler')
router.use('/admin', authenticator, admin)
router.use('/equipments', authenticator, equipments)
router.get('/sign_up', userController.SignUpPage)
router.post('/sign_up', userController.SignUp)
router.get('/log_in', userController.logInPage)
router.post('/log_in', passport.authenticate('local', { failureRedirect: '/log_in', failureFlash: true }), userController.logIn)
router.get('/logout', userController.logout)
router.get('/aboutUs', authenticator, (req, res) => { res.render('aboutUs') })

router.get('/', authenticator, (req, res) => res.redirect('/equipments/:category'))
router.use('/', generalErrorHandler)
module.exports = router
